import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header/navbar";
import { ClerkProvider } from "@clerk/nextjs";
import StoreProvider from "@/lib/redux/StoreProvider";

const lato = Lato({ weight: "400" });

export const metadata: Metadata = {
  title: "E-commerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <ClerkProvider>
        <html lang='en'>
          <body className={lato.className}>
            <Navbar />

            {children}
          </body>
        </html>
      </ClerkProvider>
    </StoreProvider>
  );
}
